services:
  browser-tools-dev:
    build: .
    container_name: browser-tools-mcp-dev
    ports:
      # Browser Tools Server ports (fallback range)
      - "3025:3025"
      - "3026:3026"
      - "3027:3027"
      - "3028:3028"
      - "3029:3029"
      - "3030:3030"
      - "3031:3031"
      - "3032:3032"
      - "3033:3033"
      - "3034:3034"
      - "3035:3035"
    volumes:
      # Mount source code for development (commented out to use COPY from Dockerfile)
      # - ./browser-tools-mcp:/app/browser-tools-mcp
      # - ./browser-tools-server:/app/browser-tools-server
      # - ./chrome-extension:/app/chrome-extension
      # - ./docs:/app/docs
      # Mount downloads directory for screenshots
      - ./downloads:/home/browseruser/Downloads
      # Mount node_modules to avoid rebuilding
      - browser-tools-mcp-node_modules:/app/browser-tools-mcp/node_modules
      - browser-tools-server-node_modules:/app/browser-tools-server/node_modules
    environment:
      - NODE_ENV=development
      - BROWSER_TOOLS_PORT=3025
      - BROWSER_TOOLS_HOST=0.0.0.0
      - DISPLAY=${DISPLAY}
      - ENABLE_HTTPS=${ENABLE_HTTPS:-false}
      - CERT_DIR=/app/certs
    stdin_open: true
    tty: true
    restart: unless-stopped
    # Enable Chrome sandbox for better security
    security_opt:
      - seccomp:unconfined
    # Add necessary capabilities for Chrome
    cap_add:
      - SYS_ADMIN
    # Share host network for better connectivity
    network_mode: host

  # Optional: Add a development server for hot reloading
  browser-tools-server-dev:
    build: .
    container_name: browser-tools-server-dev
    ports:
      - "3025:3025"
    volumes:
      - ./browser-tools-server:/app/browser-tools-server
      - browser-tools-server-node_modules:/app/browser-tools-server/node_modules
      - ./downloads:/home/browseruser/Downloads
    environment:
      - NODE_ENV=development
      - BROWSER_TOOLS_PORT=3025
      - BROWSER_TOOLS_HOST=0.0.0.0
    command: >
      bash -c "
        echo 'Starting Browser Tools Server in development mode...' &&
        cd /app/browser-tools-server &&
        npm run build &&
        npm start
      "
    restart: unless-stopped
    profiles:
      - server-only

volumes:
  browser-tools-mcp-node_modules:
  browser-tools-server-node_modules:

networks:
  default:
    name: browser-tools-network
