#!/bin/bash

echo "🚀 BrowserTools MCP Setup Script"
echo "=================================="
echo ""

echo "📋 Installation Steps:"
echo "1. ✅ Chrome extension downloaded and extracted to chrome-extension/"
echo "2. ✅ BrowserTools server installed globally"
echo "3. ✅ Cursor MCP configuration created at ~/.cursor/mcp.json"
echo ""
echo "🔧 Next Steps:"
echo ""
echo "1. Install Chrome Extension:"
echo "   - Open Chrome and go to chrome://extensions/"
echo "   - Enable 'Developer mode' (toggle in top right)"
echo "   - Click 'Load unpacked'"
echo "   - Select the 'chrome-extension' folder in this project"
echo "   - You should see 'BrowserToolsMCP' in your extensions list"
echo ""
echo "2. Start BrowserTools Server:"
echo "   - Run this command in a new terminal:"
echo "     npx @agentdeskai/browser-tools-server@1.2.0"
echo ""
echo "3. Restart Cursor:"
echo "   - Close and reopen Cursor to load the MCP configuration"
echo "   - Check Cursor settings > Features > MCP Servers"
echo "   - You should see 'browser-tools' listed with a green circle"
echo ""
echo "4. Open Chrome DevTools:"
echo "   - Right-click on any webpage and select 'Inspect'"
echo "   - Look for the 'BrowserToolsMCP' panel in the DevTools"
echo ""
echo "🎉 You're all set! Try asking Cursor:"
echo "   - 'Enter debugger mode'"
echo "   - 'Take a screenshot'"
echo "   - 'Check console logs'"
echo "   - 'Run audit mode'"
echo ""

# Check if port 3025 is available
if lsof -Pi :3025 -sTCP:LISTEN -t >/dev/null ; then
    echo "⚠️  Warning: Port 3025 is already in use. You may need to stop the existing process."
    echo "   Run: lsof -ti:3025 | xargs kill -9"
    echo ""
fi

echo "📝 Troubleshooting:"
echo "- If MCP server doesn't connect, try refreshing Cursor settings"
echo "- If no logs appear, make sure Chrome DevTools is open"
echo "- If screenshots fail, check the BrowserTools panel in DevTools"
echo "- For more help: https://browsertools.agentdesk.ai/installation"
